// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Firstname pgtype.Text
	Lastname  pgtype.Text
	Username  string
	Password  pgtype.Text
}
