// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (firstname, lastname, username, password)
VALUES ($1, $2, $3, $4)
RETURNING firstname, lastname, username, password
`

type CreateUserParams struct {
	Firstname pgtype.Text
	Lastname  pgtype.Text
	Username  string
	Password  pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Firstname,
		arg.Lastname,
		arg.Username,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.Firstname,
		&i.Lastname,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const fetchUser = `-- name: FetchUser :one
SELECT firstname, lastname, username, password
FROM "user"
WHERE username = $1
`

func (q *Queries) FetchUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, fetchUser, username)
	var i User
	err := row.Scan(
		&i.Firstname,
		&i.Lastname,
		&i.Username,
		&i.Password,
	)
	return i, err
}
